// LADX brand tokens — single source of truth for colour, spacing, typography.
// Never hardcode hex values in app code. Always use these.

export const colors = {
  ink: "#0F1A24",
  teal: "#3FBFB5",
  white: "#FFFFFF",

  // Derived neutrals — generated by lightening / darkening ink for surfaces.
  ink50: "#F4F6F8",
  ink100: "#E4E8EC",
  ink200: "#C5CDD4",
  ink300: "#9AA6B0",
  ink400: "#6F7E8B",
  ink500: "#475866",
  ink600: "#33424E",
  ink700: "#222E37",
  ink800: "#15212B",
  ink900: "#0F1A24",

  // Teal scale.
  teal50: "#EAF8F7",
  teal100: "#CDEFEC",
  teal200: "#9CDFD9",
  teal300: "#6BCFC6",
  teal400: "#3FBFB5",
  teal500: "#2EA39A",
  teal600: "#23857E",
  teal700: "#1B6862",
  teal800: "#114A46",
  teal900: "#0A302D",

  // Functional.
  success: "#2EA34B",
  warning: "#E0A53A",
  danger: "#D24747",
  info: "#3FBFB5",
} as const;

export const fonts = {
  sans: ['"Inter"', "system-ui", "-apple-system", "sans-serif"].join(", "),
  mono: ['"JetBrains Mono"', "ui-monospace", "Menlo", "monospace"].join(", "),
} as const;

export const radii = {
  sm: "0.25rem",
  md: "0.5rem",
  lg: "0.75rem",
  xl: "1rem",
  full: "9999px",
} as const;

export const spacing = {
  px: "1px",
  0: "0",
  1: "0.25rem",
  2: "0.5rem",
  3: "0.75rem",
  4: "1rem",
  6: "1.5rem",
  8: "2rem",
  12: "3rem",
  16: "4rem",
  24: "6rem",
} as const;

export type LadxColor = keyof typeof colors;
