// Re-exports the auto-generated TS bindings from the Rust `ladx-types` crate.
// Regenerated by `pnpm test:rust`. Do not edit `./generated/` files directly.

export type { AuditEntry } from "./generated/AuditEntry";
export type { DocumentKind } from "./generated/DocumentKind";
export type { HmiPlatform } from "./generated/HmiPlatform";
export type { HmiScreen } from "./generated/HmiScreen";
export type { MemoryCollection } from "./generated/MemoryCollection";
export type { MemoryEntry } from "./generated/MemoryEntry";
export type { ParseResult } from "./generated/ParseResult";
export type { PlcLanguage } from "./generated/PlcLanguage";
export type { PlcRoutine } from "./generated/PlcRoutine";
export type { Project } from "./generated/Project";
export type { ProjectManifest } from "./generated/ProjectManifest";
export type { ProjectStats } from "./generated/ProjectStats";
export type { RegulatoryRegime } from "./generated/RegulatoryRegime";
export type { RoutineRef } from "./generated/RoutineRef";
export type { DiagnosticSeverity } from "./generated/DiagnosticSeverity";
export type { Tag } from "./generated/Tag";
export type { TagRef } from "./generated/TagRef";
export type { ValidatorDiagnostic } from "./generated/ValidatorDiagnostic";
export type { ValidatorReport } from "./generated/ValidatorReport";
export type { VendorKind } from "./generated/VendorKind";

// ── Feature flags ────────────────────────────────────────────────────────
// The list is defined in `ladx-types` so the vendor bridges and the UI
// cannot disagree about what exists or what it is called.
export type { FeatureFlag } from "./generated/FeatureFlag";
export type { FeatureSet } from "./generated/FeatureSet";
export type { Maturity } from "./generated/Maturity";

// ── Vendor integrations ──────────────────────────────────────────────────
// Generated from `ladx-vendor`. "Not installed" is an ordinary answer here
// rather than an error, so the UI reads these rather than catching
// something.
export type { Availability } from "./generated/vendor/Availability";
export type { UnusableReason } from "./generated/vendor/UnusableReason";
export type { VendorCapabilities } from "./generated/vendor/VendorCapabilities";
export type { VendorStatus } from "./generated/vendor/VendorStatus";

// ── LADX IR ──────────────────────────────────────────────────────────────
// Generated from the `ladx-ir` crate into ./generated/ir/. Namespaced in its
// own directory because ts-rs writes one flat file per type name, so two
// crates exporting the same name overwrite each other silently.
export type { IrProject } from "./generated/ir/IrProject";
export type { Vendor } from "./generated/ir/Vendor";
export type { Pou } from "./generated/ir/Pou";
export type { PouKind } from "./generated/ir/PouKind";
export type { PouBody } from "./generated/ir/PouBody";
export type { Rung } from "./generated/ir/Rung";
export type { Logic } from "./generated/ir/Logic";
export type { Instruction } from "./generated/ir/Instruction";
export type { OpCode } from "./generated/ir/OpCode";
export type { Operand } from "./generated/ir/Operand";
export type { VendorDetail } from "./generated/ir/VendorDetail";
export type { DataTypeDef } from "./generated/ir/DataTypeDef";
// How well something survived a conversion. Shared by every importer and
// exporter, so a report reads the same whatever produced it.
export type { Fidelity } from "./generated/ir/Fidelity";
export type { FidelityNote } from "./generated/ir/FidelityNote";
export type { ConversionReport } from "./generated/ir/ConversionReport";
export type { FieldDevice } from "./generated/ir/FieldDevice";
export type { IoDirection } from "./generated/ir/IoDirection";
// `Tag` and `DataType` exist in both crates with different shapes; the IR ones
// are aliased rather than re-exported bare, so a wrong import is a type error
// instead of a surprise at runtime.
export type { Tag as IrTag } from "./generated/ir/Tag";
export type { DataType as IrDataType } from "./generated/ir/DataType";
// Same reason: @ladx/studio has a `DeviceKind` of its own spelled in
// SCREAMING_CASE. Two enums, same name, different members.
export type { DeviceKind as IrDeviceKind } from "./generated/ir/DeviceKind";
